prescriptive_spatial = [
    {
        'Prompt': 'A bookshelf is placed against a wall, with a vase on the top shelf and a lamp on the floor. The lamp should be positioned a short distance from the wall.',
        'Reference Caption': 'A bookshelf against a wall, with a vase on the top shelf and a lamp on the floor, slightly away from the wall.',
        'Assessment Point': 'Positioning an object (lamp) at a small distance from a vertical reference (wall).',
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 1,
    },
    {
        'Prompt': 'A bicycle is leaning against a wall, with a helmet hanging from the handlebars. Place a water bottle on the ground next to the bicycle, not too close to the wall.',
        'Reference Caption': 'A bicycle leaning against a wall, with a helmet hanging from the handlebars, and a water bottle on the ground nearby but not too close to the wall.',
        'Assessment Point': 'Combining adjacency (next to bicycle) with a non-specific distance from the wall.',
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 2,
    },
    {
        'Prompt': "A person is standing in a room, with a chair in front of them and a table behind them. Place a book on the table, slightly to the right of the person's shoulder.",
        'Reference Caption': "A person standing in a room, with a chair in front of them and a table behind them, and a book on the table slightly to the right of the person's shoulder.",
        'Assessment Point': 'Body-relative positioning (right shoulder) using vague spatial language.',
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 3,
    },
    {
        'Prompt': 'A garden has a small pond in the center, with a fountain in the pond. Place a bench on the edge of the pond, not too close to the fountain.',
        'Reference Caption': 'A garden with a small pond in the center, a fountain in the pond, and a bench on the edge of the pond, positioned a short distance from the fountain.',
        'Assessment Point': 'Edge-based placement with general radial distance from central feature.',
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 4,
    },
    {
        'Prompt': 'A kitchen has a sink and stove, with a refrigerator on the opposite side of the room. Place a trash can near the sink, and a toaster just beside the stove.',
        'Reference Caption': 'A kitchen with a sink and stove, a refrigerator on the opposite side of the room, a trash can near the sink, and a toaster close to the stove.',
        'Assessment Point': 'Simultaneous proximity-based placement for multiple objects relative to different fixtures.',
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 5,
    },

           {
        'Prompt': 'A living room has a TV on the wall, with a coffee table in front of it. Place a vase on the coffee table.',
        'Reference Caption': 'A living room with a TV on the wall, a coffee table in front of it, and a vase on the coffee table.',
        'Assessment Point': 'Layered positioning (on surface + distance from wall-mounted object).',
        'Evaluation Points': ['TV is wall-mounted and visually distinct from freestanding objects', 'Coffee table is positioned directly in front of the TV', "Vase is clearly placed on the coffee table's surface", 'Hierarchical placement: TV (wall) → coffee table (floor) → vase (table surface)'],
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 6,
    },
    {
        'Prompt': 'A bedroom has a bed against a wall, with a nightstand next to it. Place a lamp on the nightstand, just a little offset from the bed.',
        'Reference Caption': 'A bedroom with a bed against a wall, a nightstand next to it, and a lamp on the nightstand, slightly separated from the bed.',
        'Assessment Point': 'Object placement on a surface with a small spatial buffer from another object.',
        'Evaluation Points': ['Bed makes direct contact with wall surface', 'Nightstand placed adjacent to bed with shared edge', 'Lamp fully contained on nightstand surface', 'Lamp slightly offset from bed frame edge', 'Vertical alignment: lamp positioned toward bed-side of nightstand'],
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 7,
    },
    {
        'Prompt': 'A museum has a exhibit with a large dinosaur model, a smaller model of a triceratops, and a display case. Place the triceratops model a short distance from the dinosaur model, and the display case just beyond the triceratops model.',
        'Reference Caption': 'A museum with an exhibit, a large dinosaur model, a smaller model of a triceratops a short distance away, and a display case positioned just beyond the triceratops model.',
        'Assessment Point': 'Sequential distance relationships between exhibit elements using relative spacing.',
        'Evaluation Points': ['Clear size differentiation between dinosaur and triceratops models', 'Noticeable gap maintained between dinosaur and triceratops', 'Display case placed shortly beyond triceratops model', 'Progressive spacing: dinosaur → triceratops → display case forms sequence', 'All elements share common exhibit floor plane'],
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 8,
    },
    {
        'Prompt': 'A small bird is perched on the branch of a tall tree, with a nest a little to the left and just below it.',
        'Reference Caption': 'A small bird is perched on a tree branch, with a nest a bit lower and to the left of the branch.',
        'Assessment Point': 'Combined vertical (below) and horizontal (left) positioning in approximate terms.',
        'Evaluation Points': ["Bird's position locked to branch surface", 'Nest located vertically below branch plane', "Clear leftward horizontal offset from branch's vertical projection", 'Diagonal spatial relationship: nest southwest/northeast of branch (depending on perspective)', "Proportional placement: gentle leftward shift maintains visual connection between elements"],
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 9,
    },
    {
        'Prompt': 'Position a bicycle at the top of a staircase, with a skateboard at the bottom step. The bicycle should be facing upwards, while the skateboard faces downwards.',
        'Reference Caption': 'A bicycle is positioned at the top of a staircase, facing upwards, while a skateboard is placed at the bottom step, facing downwards.',
        'Assessment Point': 'Positioning at opposite ends of a structure with opposing directional orientations.',
        'Category': 'Compositional',
        'Subcategory': 'Prescriptive Spatial',
        'id': 10,
    },
        {
            'Prompt': 'A person is standing in front of a bookshelf, with a book in their hand. Place a lamp on the table beside them, slightly above their elbow.',
            'Reference Caption': 'A person is standing in front of a bookshelf, holding a book, with a lamp on a table beside them, slightly above their elbow.',
            'Assessment Point': "Object placement relative to a person's body part (beside and above elbow).",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 11,
        },
        {
            'Prompt': 'A cat is sitting on a windowsill, with a bird feeder hanging outside the window. The feeder should be slightly to the right of the window.',
            'Reference Caption': 'A cat is sitting on a windowsill, with a bird feeder hanging outside the window, slightly to the right of the window.',
            'Assessment Point': "Spatial relation 'slightly to the right of' for object placement relative to a window",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 12,
        },
        {
            'Prompt': 'Position a toy box at the foot of a bed, with a stuffed animal sitting on top of it. The animal should be facing towards the headboard.',
            'Reference Caption': 'A toy box is positioned at the foot of a bed, with a stuffed animal sitting on top of it, facing towards the headboard.',
            'Assessment Point': "Orientation 'facing towards' relative to a specific object (headboard)",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 13,
        },
        {
            'Prompt': 'A person is standing in a kitchen, with a refrigerator behind them. Place a pot on the stove in front of them, slightly to the left.',
            'Reference Caption': 'A person is standing in a kitchen, with a refrigerator behind them, and a pot on the stove in front of them, slightly to the left.',
            'Assessment Point': "Spatial relations 'behind', 'in front of', and 'slightly to the left' relative to person's position",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 14,
        },
        {
            'Prompt': "A dog is lying on a rug, with a ball nearby. The ball should be slightly to the right of the dog's head.",
            'Reference Caption': 'A dog is lying on a rug, with a ball slightly to the right of its head.',
            'Assessment Point': "Spatial relation 'slightly to the right of' relative to a body part (dog's head)",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 15,
        },
        {
            'Prompt': "Position a chair at the head of a table, with a vase on the table in front of it. The vase should be slightly above the chair's armrest.",
            'Reference Caption': "A chair is positioned at the head of a table, with a vase on the table in front of it, slightly above the chair's armrest.",
            'Assessment Point': "Spatial relations 'in front of' and 'slightly above' relative to object parts (chair armrest)",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 16,
        },
        {
            'Prompt': "A person is sitting on a couch, with a bookshelf behind them. Place a book on the shelf, slightly to the left of the person's head.",
            'Reference Caption': "A person is sitting on a couch, with a bookshelf behind them, and a book on the shelf, slightly to the left of the person's head.",
            'Assessment Point': "Spatial relations 'behind' and 'slightly to the left of' relative to body part (person's head)",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 17,
        },
        {
            'Prompt': "A car is parked in a driveway, with a bicycle leaning against the fence. The bicycle should be slightly to the right of the car's rear bumper.",
            'Reference Caption': "A car is parked in a driveway, with a bicycle leaning against the fence, slightly to the right of the car's rear bumper.",
            'Assessment Point': 'Relative positioning (right) with respect to a specific object part (rear bumper).',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 18,
        },
{
    'Prompt': 'A bicycle leans against the west wall of a garage. A toolbox is placed a short distance to the right of the bicycle, and a car parked directly north of both objects faces southward.',
    'Reference Caption': 'The bicycle is positioned against the west wall. The toolbox is just to its right (east), leaving a noticeable gap. The car faces south and is parked parallel to the north side of the bicycle and toolbox, aligned perpendicular to the wall.',
    'Assessment Point': 'Cardinal directions (west, east, north) combined with right/left relative positioning and object alignment using approximate spatial phrasing.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 19,
},
        {
            'Prompt': 'Position a coffee mug halfway between a laptop and a desk lamp. The lamp is on the far left edge of the table, and the laptop screen faces away from the mug.',
            'Reference Caption': 'The lamp is at the table’s left edge. The mug sits precisely midway between the lamp and laptop, with the laptop’s screen angled opposite to the mug’s position (e.g., if the mug is center-left, the laptop faces right).',
            'Assessment Point': 'Midpoint positioning between objects and orientation (facing away) relative to another object.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 20,
        },
        {
            'Prompt': 'A bluebird perches on the tallest branch of a pine tree. A squirrel sits on a lower branch diagonally to the bird’s left, and a hollow nest is visible directly below the squirrel.',
            'Reference Caption': 'The bluebird is on the highest branch. The squirrel occupies a lower branch positioned diagonally left-downward from the bird. The nest is vertically aligned under the squirrel’s branch, not overlapping the trunk.',
            'Assessment Point': 'Diagonal (left-downward) and vertical (directly below) positioning relative to referenced objects.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 21,
        },
        {
            'Prompt': 'Arrange three suitcases: a large one centered in a room, a medium one 45 degrees to its front-right, and a small one 45 degrees to its front-left. All face outward radially from the large suitcase.',
            'Reference Caption': 'The large suitcase is central. The medium and small suitcases form symmetrical angles (45°) in front of it, positioned like spokes on a wheel, each rotated to face away from the center.',
            'Assessment Point': 'Symmetrical angular placement (45°) and radial orientation from a central object.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 22,
        },
{
    'Prompt': 'A cat sleeps under a dining chair. A bowl of milk is placed just northeast of the chair, and a toy mouse sits halfway between the bowl and the chair’s front legs.',
    'Reference Caption': 'The cat is beneath the chair. The milk bowl is northeast (45° angle) of the chair with a small gap. The toy mouse lies exactly midway between the bowl and the chair’s front legs.',
    'Assessment Point': 'Cardinal direction (northeast) positioning and midpoint alignment between objects using soft distance phrasing.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 23,
},
{
    'Prompt': 'A streetlight stands at the intersection’s northwest corner. A stop sign is placed a short distance to the east, and a fire hydrant is located just south of the sign, aligned with the streetlight’s base.',
    'Reference Caption': 'The streetlight is at the NW corner. The stop sign is a little way to the east (forming a horizontal line). The hydrant is just south of the sign, creating a vertical line down from it and staying aligned east-west with the streetlight.',
    'Assessment Point': 'Cardinal directions (NW, E, S) and multi-axis alignment (horizontal/vertical lines relative to objects) using approximate distance language.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 24,
},

        {
            'Prompt': 'On a kitchen counter, place a cutting board to the right of the sink. Position a knife vertically on the board’s left edge and a carrot horizontally on its right edge.',
            'Reference Caption': 'The cutting board is immediately right of the sink. The knife stands upright on the board’s left side, while the carrot lies flat on the right side, parallel to the counter’s edge.',
            'Assessment Point': 'Relative horizontal positioning (right/left) and object orientation (vertical vs. horizontal alignment)',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 25,
        },
        {
            'Prompt': 'Align three rocks in a straight diagonal line from the top-left to bottom-right of a sandbox. The middle rock is twice as large as the others and touches both.',
            'Reference Caption': 'Three rocks form a diagonal (NW to SE). The central rock is larger and physically connects to the two smaller rocks, which are at the diagonal’s endpoints.',
            'Assessment Point': 'Diagonal spatial sequencing (NW-SE) with size-dependent connectivity constraints',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 26,
        },
        {
            'Prompt': 'On a bookshelf, place a red book vertically in the top-left shelf. Lay a green book horizontally in the bottom-right shelf, and position a vase halfway between them diagonally, closer to the front edge.',
            'Reference Caption': 'The red book stands upright on the top-left shelf. The green book lies flat on the bottom-right shelf. The vase sits diagonally between them, shifted toward the front (not centered depth-wise).',
            'Assessment Point': 'Cross-quadrant diagonal positioning with combined orientation (vertical/horizontal) and depth prioritization',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 27,
        },
        {
            'Prompt': "A microwave door is open, with a mug placed inside. A metal spoon lies to the left of the microwave, and a plate is positioned directly below the microwave's door.",
            'Reference Caption': 'The mug is fully inside the open microwave. The spoon is placed distinctly to the microwave’s left (not overlapping), and the plate sits vertically aligned below the microwave door, not touching the appliance.',
            'Assessment Point': "Precision in 'inside,' 'left of,' and 'below' relationships with clear spatial separation",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 28,
        },
        {
            'Prompt': 'A white bookshelf stands against a wall. On its middle shelf, a potted plant sits between two stacks of books, with a framed photo leaning against the left stack.',
            'Reference Caption': 'The plant is centered on the middle shelf, flanked by equal book piles. The photo rests vertically against the left book pile’s side, not lying flat.',
            'Assessment Point': "Accurate interpretation of 'between' for centering and 'against' for vertical placement",
            'Evaluation Points': ['Bookshelf orientation flush against wall surface', 'Middle shelf identification (neither top nor bottom)', 'Plant equidistant from both book stacks with symmetrical spacing', 'Book stacks of comparable width/height framing the plant', "Photo positioned vertically (upright) against left stack's side", 'No overlap between photo and plant/books beyond contact point'],
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 29,
        },
        {
            'Prompt': 'At a crosswalk, a bicycle waits behind a stopped delivery truck. A pedestrian walks across the street to the truck’s right, aligned with its rear wheels.',
            'Reference Caption': 'The truck is foremost, bicycle positioned clearly behind it. The pedestrian crosses at the truck’s right side, vertically aligned with its back wheels, not in front/behind.',
            'Assessment Point': "Clarity in hierarchical 'behind' prioritization and 'aligned with' for lateral positioning",
            'Evaluation Points': ['Clear front-to-back hierarchy: truck > bicycle in lane', 'Bicycle fully visible behind truck (no partial occlusion)', "Pedestrian trajectory perpendicular to truck's right side", "Pedestrian's lateral position matches truck's rear wheel line", 'No forward/backward offset between pedestrian and rear wheels', 'Crosswalk markings visible between all elements'],
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 30,
        },
        {
            'Prompt': 'On a patio table, a coffee cup sits centered on a saucer. A teaspoon points northwest across the saucer’s right edge, while a napkin lies folded under the saucer’s left side.',
            'Reference Caption': 'Cup/saucer centered. Teaspoon diagonally crosses the saucer’s right half. Napkin is partially visible under the saucer’s left edge, not fully covered.',
            'Assessment Point': "Execution of 'centered,' cardinal-angled placement, and partial 'under' relationships",
            'Evaluation Points': ["Cup/saucer alignment at table's geometric center", 'Teaspoon handle orientation: NW-SE diagonal (135° angle)', "Teaspoon intersects saucer's right perimeter", "Napkin edge visible protruding from saucer's left side", 'Partial napkin coverage (≤50% visible) under saucer', 'No contact between teaspoon and napkin'],
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 31,
        },
{
    'Prompt': 'In a fish tank, a castle decoration stands to the right of a bubbling treasure chest. Three pebbles form a straight line starting just in front of the castle, extending leftward.',
    'Reference Caption': 'Treasure chest (left) and castle (right) inside tank. Pebbles form a horizontal line beginning at the front of the castle base, progressing leftward, spaced evenly.',
    'Assessment Point': 'Relative horizontal positioning (left/right) and linear spatial progression from a reference point.',
    'Evaluation Points': ['Clear left/right distinction between treasure chest and castle', 'Pebble line originates just in front of the castle base', 'Linear pebble arrangement maintains straight leftward trajectory', 'Equal spacing between all three pebbles', 'All elements submerged underwater (tank context)'],
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 32,
},

        {
            'Prompt': 'On a doctor’s desk, a stethoscope coils clockwise around a clipboard. A pen lies diagonally across the clipboard’s top-right corner, pointing northeast.',
            'Reference Caption': 'Stethoscope forms a circular loop enclosing the clipboard. Pen crosses the clipboard’s upper right corner at a 45-degree angle, tip facing NE.',
            'Assessment Point': 'Circular spatial enclosure (clockwise) and angular/directional precision (45-degree NE orientation)',
            'Evaluation Points': ['Stethoscope completely encircles clipboard in clockwise spiral', 'Pen orientation precisely at 45° angle from clipboard corner', 'Pen tip alignment matches compass NE direction', 'No physical overlap between stethoscope and pen', 'Clipboard remains fully visible within coiled stethoscope'],
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 33,
        },
        {
            'Prompt': 'On a chessboard, the white queen stands two squares in front of the black king. A captured knight lies flipped over to the king’s immediate left.',
            'Reference Caption': 'White queen is placed two squares vertically ahead of the black king. The defeated knight is horizontally adjacent to the king’s left, turned upside down.',
            'Assessment Point': 'Cheboard-specific vertical/horizontal positioning and adjacency relationships',
            'Evaluation Points': ['Queen positioned 2 squares vertically (same file) ahead of king', 'Knight placed in immediate adjacent left square (same rank)', 'Clear visual distinction between upright and flipped pieces', 'Proper chessboard grid alignment for all pieces', 'Color contrast between white/black pieces maintained'],
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 34,
        },
{
    'Prompt': 'A red umbrella is open on the beach, with a green towel placed to its left. A yellow bucket is positioned behind the umbrella, and a sandcastle is built in front of the towel. All items are spaced with generous separation.',
    'Reference Caption': 'The red umbrella is centrally placed, with the green towel clearly to its left (no overlap). The yellow bucket is directly behind the umbrella, and the sandcastle is positioned in front of the towel. All objects maintain ample spacing in a diamond-like layout.',
    'Assessment Point': 'Multi-object relative positioning (left/right/front/behind) with clear spatial buffers between items.',
    'Evaluation Points': ['Quadrilateral spatial configuration (umbrella central anchor)', 'Visible separation between all object pairs', "Bucket positioned along umbrella's central vertical axis (behind)", "Sandcastle aligned with towel's frontal plane", 'Cardinal direction preservation (left/right/front/behind consistency)'],
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 35,
},

        {
            'Prompt': 'A stone bird statue sits atop a fountain in a garden. A wooden bench is positioned to the fountain’s right, facing a gravel path that runs along the garden’s left boundary.',
            'Reference Caption': 'The fountain is central, with the statue on its peak. The bench is placed to the fountain’s immediate right, angled to face the gravel path on the garden’s far left side. The bench and path form a diagonal line across the scene.',
            'Assessment Point': 'Positioning relative to a central object (fountain) with directional relationships (right/left) and diagonal alignment',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 36,
        },
        {
            'Prompt': 'On a three-tiered bookshelf: a vase occupies the top-left shelf, a round clock is centered on the middle shelf, and a potted plant sits on the bottom-right shelf. The plant’s vines cascade over the shelf edge.',
            'Reference Caption': 'Clear vertical separation: vase (top-left), clock (middle-center), plant (bottom-right). The plant’s leaves visibly droop below the bottom shelf. No overlapping between shelves.',
            'Assessment Point': 'Vertical tier organization with quadrant-specific placement (top-left/middle-center/bottom-right) and containment within shelves',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 37,
        },
        {
            'Prompt': 'A dining table has a fruit bowl at its center. To the bowl’s left is a plate, and to its right is a glass. A napkin is folded beneath a fork, which lies to the plate’s left.',
            'Reference Caption': 'Bowl at center, plate directly left of bowl, glass directly right. The fork is placed left of the plate, with the napkin positioned precisely under the fork (not adjacent to the plate or bowl).',
            'Assessment Point': "Precise left/right positioning relative to a central object and 'beneath' relationship",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 38,
        },
        {
            'Prompt': 'In a parking lot: a blue car is parked left of a red truck. A motorcycle faces east in front of the car, while a bicycle leans against a post behind the truck.',
            'Reference Caption': 'Horizontal alignment: truck (right), car (left of truck). Motorcycle is ahead of the car, facing away from both vehicles. Bicycle is behind the truck, separate from the car’s area.',
            'Assessment Point': 'Horizontal left/right alignment combined with front/behind positioning of multiple vehicles',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 39,
        },
        {
            'Prompt': 'An office desk has a centered monitor. A lamp stands to the monitor’s left, angled toward it. A notebook lies to the monitor’s right, and a coffee cup is placed behind the lamp.',
            'Reference Caption': 'Monitor at center. Lamp left of monitor, tilted inward. Notebook aligned to the monitor’s right edge. Cup positioned behind the lamp (not beside it), creating depth.',
            'Assessment Point': 'Directional placement (left/right/behind) and depth relationships around a central object',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 40,
        },
        {
            'Prompt': 'In a playground: a slide faces north, a swing set is southwest of the slide, and a seesaw sits east of the swings. All equipment faces the playground’s center.',
            'Reference Caption': 'Slide (north-facing) anchors the scene. Swings are diagonally southwest of the slide, seesaw east of swings. All structures angle inward toward an imaginary central point.',
            'Assessment Point': 'Cardinal direction-based placement (north/southwest/east) and inward-facing orientation',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 41,
        },
        {
            'Prompt': 'A kitchen stove has a microwave mounted above it. Inside the microwave is a spatula. A plate rests to the stove’s right, and an open cabinet door is to its left.',
            'Reference Caption': 'Microwave directly above stove. Spatula visible inside microwave (door closed?). Plate on counter right of stove. Cabinet door open on the left side, revealing interior.',
            'Assessment Point': 'Vertical alignment, containment, and horizontal positioning relative to primary objects',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 42,
        },
        {
            'Prompt': 'A street scene: a bus stop sign stands on the left. A bench is to the sign’s right, and a trash can is behind the bench. A bicycle rack is positioned in front of the sign.',
            'Reference Caption': 'Sign (far left), bench directly to its right. Trash can behind bench, not blocking it. Bike rack placed between sign and viewer, distinct from other elements.',
            'Assessment Point': 'Front/back positioning and maintaining unobstructed element placement',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 43,
        },
        {
            'Prompt': 'A tree stands central in a park. Northeast of the tree is a south-facing picnic table. Southeast of the table is a trash can. Directly west of the tree is a signpost.',
            'Reference Caption': 'Tree at center. Picnic table diagonally northeast, oriented to face south. Trash can southeast of table (not near tree). Signpost west of tree, forming a horizontal axis.',
            'Assessment Point': 'Cardinal direction comprehension and object orientation alignment',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 44,
        },
        {
            'Prompt': 'A red book is positioned to the left of a blue vase on a wooden shelf. A green pot is placed above the vase but aligned with the right edge of the book.',
            'Reference Caption': 'The red book is on the shelf’s left side, the blue vase directly to its right. The green pot hovers vertically above the vase but horizontally aligns with the book’s right edge, creating a diagonal relationship between pot, vase, and book.',
            'Assessment Point': 'Horizontal and vertical object positioning with cross-element alignment',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 45,
        },
        {
            'Prompt': 'A coffee cup sits inside a microwave with its handle facing the door. A plate is placed on the counter below the microwave, and a spoon lies to the left of the plate.',
            'Reference Caption': 'The microwave door is closed, with the cup’s handle visibly angled toward it. The plate is centered below the microwave, and the spoon is positioned strictly to the plate’s left (no overlap).',
            'Assessment Point': 'Containment, object directional orientation, and adjacent placement',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 46,
        },
        {
            'Prompt': 'A bicycle leans against a tree, its front wheel pointing toward a bench placed diagonally across the path. A dog sits beside the bench, facing the bicycle.',
            'Reference Caption': 'The bicycle’s front wheel angles toward the bench, which is placed at a 45-degree angle relative to the path. The dog sits adjacent to the bench’s far side, oriented toward the bicycle.',
            'Assessment Point': 'Angular object placement and directional orientation relationships',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 47,
        },
        {
            'Prompt': 'A painting hangs above a sofa, centered on the wall. A floor lamp stands to the sofa’s right, and a side table is wedged between the lamp and sofa.',
            'Reference Caption': 'The painting is perfectly centered above the sofa. The lamp is positioned to the sofa’s immediate right, with the side table bridging the gap between them without overlapping either object.',
            'Assessment Point': 'Centered alignment above an object + adjacent placement with explicit non-overlapping constraints',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 48,
        },
        {
            'Prompt': 'On a desk, position a monitor in the center with a keyboard in front of it. Place a mouse to the keyboard’s right and a coffee mug atop a notebook positioned left of the monitor.',
            'Reference Caption': 'The monitor is centered, keyboard directly in front. Mouse is aligned with the keyboard’s right edge. The notebook (left of the monitor) has the mug placed on its surface, not overlapping the monitor’s base.',
            'Assessment Point': 'Hierarchical positioning (center/front) + lateral alignment (mouse/keyboard) + compound placement (mug-on-notebook left-of-monitor)',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 49,
        },
        {
            'Prompt': 'A bird feeder hangs from a tree branch. A squirrel stands on the branch to the feeder’s left, and two birds perch on the feeder facing opposite directions.',
            'Reference Caption': 'The feeder hangs below the branch. The squirrel is on the branch’s left side relative to the feeder. Birds face 180° apart (e.g., one east, one west).',
            'Assessment Point': 'Vertical suspension (below) + relative lateral positioning on shared plane + directional opposition in orientations',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 50,
        },
        {
            'Prompt': 'A car is parked in a driveway facing the garage. A mailbox stands on the sidewalk to the driveway’s left, and a bicycle leans against a partially open garage door.',
            'Reference Caption': 'The car’s front faces the garage. The mailbox is on the sidewalk adjacent to the driveway’s left edge. The bicycle leans on the garage door, which is ajar by ~30 degrees.',
            'Assessment Point': 'Facing orientation + adjacency to boundaries (driveway/sidewalk) + interaction with movable elements (ajar door)',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 51,
        },
        {
            'Prompt': 'Stack three books: red at the bottom, blue in the middle, green on top. Place a pen diagonally across the stack from top-left to bottom-right. Rest glasses on the red book’s right corner.',
            'Reference Caption': 'Books form a vertical stack with correct color order. The pen crosses the stack diagonally without touching the surface below. Glasses sit only on the red book’s rightmost edge.',
            'Assessment Point': 'Vertical ordering precision + diagonal spatial intersection + edge-specific placement',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 52,
        },
        {
            'Prompt': 'A cat sleeps under a chair. A yarn ball is halfway under the chair’s front left leg. A lamp shines light over the chair toward the yarn.',
            'Reference Caption': 'The cat is fully under the chair. The yarn is partially obscured by the front leg. The lamp’s light cone angles downward, illuminating the yarn’s visible half.',
            'Assessment Point': 'Full/partial containment relationships + directional lighting relative to occluded objects',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 53,
        },
        {
            'Prompt': 'An open pizza box sits on a kitchen counter, missing a slice from the top right corner. A knife lies across the box’s open lid, and a folded napkin is placed to the box’s left.',
            'Reference Caption': 'The box lid is open, showing a missing slice in the upper right quadrant. The knife spans the lid’s width. The napkin is positioned to the left of the box, not touching it.',
            'Assessment Point': "Understanding spatial relationships (e.g., 'top right corner', 'across', 'to the left') and object positioning.",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 54,
        },
        {
            'Prompt': "Arrange three bookshelves in a triangular formation. Place a ladder leaning against the easternmost shelf. Position a cat on the middle shelf's top level, facing a potted plant that's 45° northeast of the western shelf.",
            'Reference Caption': "Triangular arrangement of shelves (non-linear). Ladder on eastern shelf. Cat centered on middle shelf's top. Plant positioned at precise 45° angle from western shelf.",
            'Assessment Point': "Understanding geometric formations (e.g., 'triangular', '45° northeast') and object orientation.",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 55,
        },
        {
            'Prompt': "Create a breakfast scene with a pancake stack centered on a rectangular plate. Position maple syrup pouring from northwest to southeast across the stack. Place two blueberries: one embedded in the top pancake's northeast quadrant, another beside the plate's southwest corner.",
            'Reference Caption': 'Syrup flow direction matches coordinates. Blueberry placement shows understanding of plate quadrants. Second berry outside plate at specific corner.',
            'Assessment Point': "Understanding directional flow (e.g., 'northwest to southeast') and quadrant-based positioning.",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 56,
        },
{
    'Prompt': "In a garage workshop, hang a circular saw on the west wall panel. Position a workbench a short distance to the east of the saw, with its vise grip facing north. Place safety goggles hanging from a hook slightly above the bench’s northeast corner.",
    'Reference Caption': 'Clear relative distances. Tool orientation based on cardinal directions. Elevated hook positioned at a specific corner of the bench.',
    'Assessment Point': "Approximate spatial layout and object orientation using directional cues and relative height.",
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 57,
},

        {
            'Prompt': "Arrange four chess pieces: white queen north of black king, black bishop diagonally southeast of white queen, and white knight positioned such that it's equidistant from both kings but closer to the board's eastern edge.",
            'Reference Caption': 'Complex geometric relationships. Understanding of chess piece terminology. Edge proximity awareness.',
            'Assessment Point': "Understanding complex spatial relationships (e.g., 'diagonally southeast', 'equidistant') and edge proximity.",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 58,
        },
{
    'Prompt': 'Position a satellite dish on a rooftop angled 32° northeast. Place two solar panels: one slightly to the west of the dish tilted 15° southwest, another just to the east tilted 25° southeast. Add a weather vane north of all equipment pointing west.',
    'Reference Caption': 'Angular precision with approximate horizontal placement. Relative positioning of multiple directional elements. Clear orientation hierarchy across rooftop.',
    'Assessment Point': 'Use of angular direction combined with relative cardinal placement and layout comprehension.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 59,
},
        {
            'Prompt': "In a microscope image, show three cells: a large circular cell centered, a smaller elongated cell tangent to its northwest arc, and a dividing cell positioned such that its midpoint aligns with the large cell's eastern edge.",
            'Reference Caption': 'Geometric tangency understanding. Alignment of midpoints with edges. Size differentiation with shape variations.',
            'Assessment Point': 'Understanding tangency relationships, midpoint-edge alignment, and size/shape differentiation in cellular arrangements',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 60,
        },
        {
            'Prompt': "Arrange construction vehicles: a crane's base centered on the north site, its arm extending southwest over an excavator that's positioned 30° southeast of a bulldozer. The bulldozer's blade should face the crane's cab.",
            'Reference Caption': 'Angular positioning between multiple objects. Crane arm directional extension. Vehicle orientation relationships.',
            'Assessment Point': 'Angular positioning precision, directional extension comprehension, and multi-object orientation relationships',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 61,
        },
        {
            'Prompt': 'Create a museum display with a dinosaur skeleton facing east. Position two display cases: one northwest of the skull showing teeth fossils, another southeast of the tail containing footprint casts. Add spotlighting from northeast and southwest.',
            'Reference Caption': 'Body part-specific positioning (skull vs tail). Diagonal case placements. Directional lighting sources.',
            'Assessment Point': 'Anatomic part-relative positioning, diagonal spatial relationships, and directional light source placement',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 62,
        },
        {
            'Prompt': 'Map a constellation: blue giant star at center, red dwarf 1.5 light-years northeast, planetary nebula 2 light-years southwest containing three aligned protoplanets. A comet trail arcs from northwest to southeast passing behind the blue giant.',
            'Reference Caption': 'Cosmic scale relationships. Celestial object differentiation. Trajectory understanding with occlusion.',
            'Assessment Point': 'Spatial comprehension at astronomical scales, celestial object differentiation, and trajectory occlusion understanding',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 63,
        },
        {
            'Prompt': 'A coffee mug sits on a kitchen counter. Place a spoon directly to the left of the mug, and position a bowl behind the mug but aligned to the right of the spoon.',
            'Reference Caption': 'The mug is centered on the counter. The spoon is placed immediately to the mug’s left, while the bowl is positioned diagonally behind the mug such that it aligns with the spoon’s right edge. No overlapping objects.',
            'Assessment Point': 'Left/behind positional relationships, multi-object alignment maintenance, and collision avoidance in kitchenware arrangement',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 64,
        },
        {
            'Prompt': 'In a study, center a desk lamp on a wooden desk. Stack two books vertically to the lamp’s right, and position a pen horizontally in front of the lamp, pointing northwest.',
            'Reference Caption': 'The lamp is centered on the desk. Two books stand upright to its right, touching each other. The pen lies horizontally in front of the lamp, angled toward the top-left corner of the desk.',
            'Assessment Point': 'Central positioning, vertical stacking precision, and horizontal object orientation with angular specification',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 65,
        },
{
    'Prompt': 'A round dining table has a vase in its center. Arrange three candles: one slightly north of the vase, one placed to the southwest, and one to the southeast. Ensure all candles face outward radially from the vase.',
    'Reference Caption': 'The vase is at the table’s center. Candles form a triangle around it: one directly above, one below-left, and one below-right. All candle wicks point away from the vase.',
    'Assessment Point': 'Compass directions and radial orientation using natural spatial phrasing.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 66,
},

        {
            'Prompt': 'On a patio, place a lounge chair facing west. Position a side table to its left with a drink on it. A sun hat rests on the chair’s seat, and sandals lie under the table’s right edge.',
            'Reference Caption': 'The chair faces left (west). The side table is to the chair’s left, holding a drink. The hat is on the chair seat, and sandals are partially visible under the table’s right side.',
            'Assessment Point': 'Left-right positioning, facing direction, and under placement',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 67,
        },
        {
            'Prompt': 'In a toy store, position a robot facing forward on the middle shelf. Place a toy plane diagonally behind it (top-right), flying toward the robot, and a stuffed dinosaur to the robot’s left, facing away.',
            'Reference Caption': 'The robot is centered on the shelf. The plane hovers behind and above its right shoulder, angled toward the robot. The dinosaur faces left, adjacent to the robot’s left side.',
            'Assessment Point': 'Diagonal positioning behind an object and directional facing',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 68,
        },
        {
            'Prompt': 'A bicycle faces north. Attach a basket to its front handlebar, place a helmet on the seat, and position a water bottle inside the basket, tilted 45 degrees to the right.',
            'Reference Caption': 'The bicycle faces upward. The basket is mounted on the handlebar, containing a water bottle leaning right. The helmet sits upright on the seat.',
            'Assessment Point': 'Attachment points, internal placement, and angular tilt',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 69,
        },
{
    'Prompt': 'In a park, center a picnic blanket. Put a sandwich plate at the blanket’s top edge, a drink just below the plate, and a napkin northeast of the drink, touching the blanket’s corner.',
    'Reference Caption': 'The plate is near the blanket’s upper boundary. The drink is directly below it, and the napkin is positioned diagonally top-right from the drink, aligned with the blanket’s corner.',
    'Assessment Point': 'Compass-relative positioning and edge alignment using soft spatial language.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 70,
},

        {
            'Prompt': 'On a bookshelf, place a red book on the top shelf’s far left. Center a blue vase on the middle shelf, and align a green plant on the bottom shelf’s far right. Ensure all items are vertically staggered.',
            'Reference Caption': 'The red book is top-left, the vase is middle-center, and the plant is bottom-right. No two objects share the same vertical axis.',
            'Assessment Point': 'Vertical staggering (no shared vertical axis) and precise horizontal placement (far left, center, far right) across shelves.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 71,
        },
        {
            'Prompt': 'A cat sleeps on a windowsill. Position a potted plant to the window’s left outside, and a bird feeder to the window’s right outside, both hanging at the same height as the cat.',
            'Reference Caption': 'The cat is on the sill. The plant hangs outside the window’s left pane, and the feeder hangs outside the right pane, all aligned horizontally at the cat’s eye level.',
            'Assessment Point': 'Left/right positioning relative to the window and horizontal alignment at the same height.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 72,
        },
        {
            'Prompt': 'In a garage, park a car facing the entrance. Place a toolbox 2m behind the car’s rear bumper, and position a bicycle to the toolbox’s right, facing parallel to the car.',
            'Reference Caption': 'The car faces outward. The toolbox is directly behind it, with the bicycle positioned to the toolbox’s right, both aligned along the car’s central axis.',
            'Assessment Point': 'Positioning objects behind and to the right of another object, maintaining parallel alignment to a central axis.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 73,
        },
        {
            'Prompt': 'A coffee mug is placed to the left of the stove. On the front burner of the stove sits a frying pan, and inside the mug is a teaspoon.',
            'Reference Caption': 'The stove is positioned centrally. The coffee mug is clearly to the left of the stove (not overlapping). The frying pan rests on the stove’s front burner (closest to the viewer). The teaspoon is fully inside the mug, not beside it.',
            'Assessment Point': 'Left-of positioning, placement on a specific sub-region (front burner), and containment (inside).',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 74,
        },
        {
            'Prompt': 'Arrange a vase on the top shelf of a bookshelf, centered. On the middle shelf, place a stack of three books shifted to the right edge. On the bottom shelf, align a framed photo directly below the vase.',
            'Reference Caption': 'A bookshelf with three shelves. The vase is centered on the top shelf. The middle shelf has books tightly stacked at its far right. The bottom shelf’s photo is centered vertically below the vase, creating a straight alignment.',
            'Assessment Point': 'Vertical alignment (directly below) and horizontal positioning (centered vs. far right) across shelves.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 75,
        },
        {
            'Prompt': 'Position a wooden bench under a large oak tree. A bicycle leans against the bench’s right side, facing east. A hat rests on the bench’s left edge, partially hanging off.',
            'Reference Caption': 'The bench is directly beneath the tree’s canopy. The bicycle leans vertically against the bench’s right side, with its handlebars and front wheel oriented eastward. The hat is placed on the bench’s left edge, with one-third of it dangling over the edge.',
            'Assessment Point': 'Precision in cardinal directions (east-facing), left/right object placement relative to a central object, and partial overlap management at edges.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 76,
        },
        {
            'Prompt': 'On a desk, place an open laptop to the left. To the right of the laptop, align a notebook so their top edges match. Position a coffee cup diagonally northeast of the notebook.',
            'Reference Caption': 'The laptop is open on the desk’s left side. The notebook is to the laptop’s right, with its top edge level with the laptop’s screen. The coffee cup is placed above and slightly to the right of the notebook, not overlapping either object.',
            'Assessment Point': 'Horizontal alignment of edges, left/right spatial hierarchy, and diagonal positioning (northeast interpretation) with non-overlapping constraints.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 77,
        },
        {
            'Prompt': 'In a playground, center a slide. To the slide’s left, place a swing set facing south. Behind the slide, add a sandbox that’s partially obscured by it.',
            'Reference Caption': 'The slide is central and dominant. The swing set is positioned to the slide’s left (viewer’s right), with swing seats facing away from the slide. The sandbox is placed behind the slide, with the slide’s structure blocking the lower half of the sandbox.',
            'Assessment Point': 'Central anchoring, viewer vs. object perspective (left/right distinction), directional object orientation (south-facing), and partial occlusion behind structures.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 78,
        },
        {
            'Prompt': 'A large plate sits at the center of a table. To its left, place a fork vertically aligned. To its right, position a knife with the blade facing the plate. Above the plate, place a small bowl touching its edge.',
            'Reference Caption': 'The plate is centered. The fork lies vertically (tines pointing up) to the plate’s left. The knife is to the plate’s right, blade edge directed toward the plate. The bowl hovers just above the plate’s top edge, making contact but not overlapping.',
            'Assessment Point': 'Vertical/horizontal tool alignment, left/right object symmetry relative to a centerpiece, directional blade orientation, and edge contact without overlap.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 79,
        },
        {
            'Prompt': 'Mount a TV on a wall. Directly opposite it, place a sofa. Between them, position a coffee table. A rug lies under the coffee table but does not extend under the sofa.',
            'Reference Caption': 'The TV is wall-mounted. The sofa faces it from the opposite side of the room. The coffee table is centered between them. The rug is entirely under the coffee table, stopping short before reaching the sofa’s front legs.',
            'Assessment Point': 'Opposite spatial relationships, centered intermediary object placement, and strict containment boundaries (rug limited to table area).',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 80,
        },
{
    'Prompt': 'A birdbath is centered in a garden. To its left, plant roses in a semicircle. To its right, position a stone statue a few steps away, facing north.',
    'Reference Caption': 'The birdbath is the focal point. Roses form a half-circle curving around the left side of the birdbath. The statue is placed a few steps to the birdbath’s right, oriented northward.',
    'Assessment Point': 'Left/right positioning relative to a central object with semicircular arrangement and approximate spacing.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 81,
},
{
    'Prompt': 'Place a desk against the north wall of a room. Position a chair a short distance in front of the desk. On the desk’s far right corner, angle a lamp toward the chair.',
    'Reference Caption': 'The desk touches the north wall. The chair is positioned a short but noticeable distance from the desk (not tucked in). The lamp is on the desk’s rightmost edge, tilted so its light direction faces the chair.',
    'Assessment Point': 'Cardinal direction alignment (north wall), distance estimation, and object orientation (lamp angle).',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 82,
},
        {
            'Prompt': 'A bed is against the west wall. To its right, add a nightstand. On the nightstand’s left side, place a lamp; on its right, an open book. Centered between them, add an alarm clock.',
            'Reference Caption': 'The bed is flush with the west wall. The nightstand is adjacent to the bed’s right side. The lamp occupies the nightstand’s left half, the book the right half (open with pages visible). The clock sits precisely midway between the lamp and book.',
            'Assessment Point': 'Adjacent object placement, surface-side positioning (left/right), and precise centering between objects.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 83,
        },
        {
            'Prompt': 'In a kitchen, a coffee mug sits to the left of a toaster with a slice of bread partially ejected. A knife rests diagonally across a cutting board in front of the toaster, its tip pointing toward the mug.',
            'Reference Caption': 'The toaster is centered, with the mug placed clearly to its left. The cutting board is positioned directly in front of the toaster, and the knife lies diagonally across it, oriented so its handle is near the toaster and its tip angles toward the mug.',
            'Assessment Point': 'Left/right and front/back relationships with diagonal object orientation and directional pointing.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 84,
        },
        {
            'Prompt': 'A birdbath is centered between two garden benches. A squirrel faces the birdbath from the left bench, while a cat crouches under the right bench, gazing at the squirrel.',
            'Reference Caption': 'The birdbath is equidistant between the two benches. The squirrel is on the left bench, oriented toward the birdbath. The cat is under the right bench, positioned to face the squirrel across the scene.',
            'Assessment Point': 'Centered positioning between objects, on/under placement distinctions, and directional gaze alignment.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 85,
        },
        {
            'Prompt': 'A bookshelf’s top shelf holds a potted plant to the right of a trophy. The middle shelf has three books stacked vertically, and the bottom shelf displays a framed photo leaning against its left edge.',
            'Reference Caption': 'On the top shelf, the plant is distinctly to the trophy’s right. The middle shelf’s books are aligned in a straight vertical stack. The photo on the bottom shelf touches the left shelf edge, tilted as if propped.',
            'Assessment Point': 'Understanding right/left positioning, vertical stacking alignment, and edge contact with tilt',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 86,
        },
        {
            'Prompt': 'On a desk, an open laptop faces away from the chair. A smartphone stands vertically to its right, while a notebook lies slightly behind and to the left of the laptop, with a coffee cup on its top right corner.',
            'Reference Caption': 'The laptop screen faces away from the viewer (toward the chair). The smartphone is upright and adjacent to the laptop’s right side. The notebook is placed behind and left of the laptop, with the cup resting precisely on its top right corner.',
            'Assessment Point': 'Recognizing object orientation (facing direction), vertical adjacency, and precise multi-axis positioning (behind+left)',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 87,
        },
        {
            'Prompt': 'A blue car faces a parking lot entrance. To its left, a motorcycle faces the opposite direction, and a bicycle leans against a lamppost diagonally behind the car’s right side.',
            'Reference Caption': 'The car faces forward (toward the entrance). The motorcycle is parked left of the car, rotated 180° relative to it. The bicycle is positioned diagonally behind the car’s right rear, touching the lamppost.',
            'Assessment Point': 'Interpreting directional facing (opposite orientation) and diagonal spatial relationships behind an object',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 88,
        },
        {
            'Prompt': 'In a child’s room, a teddy bear sits against the bed’s headboard. An open storybook lies on the floor to the bed’s left, and a nightstand to its right holds a lamp shining upward.',
            'Reference Caption': 'The teddy bear is centered on the bed against the headboard. The book is open on the floor, aligned with the bed’s left side. The nightstand is flush with the bed’s right, its lamp angled to illuminate upward.',
            'Assessment Point': 'Evaluating centered positioning, left/right alignment relative to furniture, and directional light orientation',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 89,
        },
        {
            'Prompt': 'A picnic basket sits centrally on a blanket, a wine bottle protruding from its left side. A plate of sandwiches is in front of the basket, flanked symmetrically by two apples.',
            'Reference Caption': 'The basket is centered on the blanket, with the wine bottle visibly extending from its left. The plate is directly in front of the basket, and the apples are equidistant from the plate’s left and right edges.',
            'Assessment Point': 'Assessing central placement with lateral extension, frontal positioning, and symmetrical flanking arrangement',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 90,
        },
        {
            'Prompt': 'A hammer lies horizontally across a toolbox on a workshop table. To its right, a screwdriver stands upright, and a nail is placed midway between the toolbox and the screwdriver’s base.',
            'Reference Caption': 'The hammer spans the toolbox’s width horizontally. The screwdriver is upright and positioned to the toolbox’s right. The nail is exactly halfway between the toolbox’s right edge and the screwdriver’s base.',
            'Assessment Point': 'Horizontal alignment across objects, right-side positioning, and precise midpoint placement between two objects.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 91,
        },
        {
            'Prompt': 'Three chairs line a waiting room: the left chair has a jacket draped over its back, the middle one is occupied by a forward-facing person, and the right chair has a suitcase under its front legs.',
            'Reference Caption': 'The left chair’s jacket hangs over the backrest. The middle chair has a person facing forward. The right chair’s suitcase is placed directly under its front legs, aligned with them.',
            'Assessment Point': 'Left-to-right sequential ordering, object placement relative to chair components (backrest/front legs), and directional orientation of human figures.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 92,
        },
        {
            'Prompt': 'A bakery display’s top shelf has a tiered cake flanked by two parallel cupcake rows. The middle shelf holds a cookie tray aligned to the left, and the lower shelf has plates stacked against its right corner.',
            'Reference Caption': 'The cake is centered on the top shelf, with identical cupcake rows on either side. The middle shelf’s cookie tray is shifted fully left. The lower shelf’s plates lean vertically against the right corner.',
            'Assessment Point': 'Vertical shelf hierarchy management, horizontal alignment (centering/flanking/left-right corner placement), and symmetrical vs asymmetrical arrangements.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 93,
        },
        {
            'Prompt': 'On a desk, place a coffee mug to the left of an open laptop facing a window. Position a notebook behind the laptop, aligned with its right edge, and a pencil midway between the mug and laptop without touching either.',
            'Reference Caption': 'The coffee mug is left of the open laptop (screen facing a visible window). The notebook sits directly behind the laptop, its left edge aligned with the laptop’s right edge. The pencil lies centered between the mug and laptop, with clear spacing from both.',
            'Assessment Point': 'Cardinal positioning (left/behind), edge-to-edge alignment, midpoint calculation with collision avoidance, and implicit screen orientation.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 94,
        },
        {
            'Prompt': 'In a garden, center a birdbath between two flower beds. Add a rabbit statue to the birdbath’s left, facing it, and a squirrel figurine on its right, facing away.',
            'Reference Caption': 'The birdbath is equidistant between two flower beds. The rabbit statue is positioned to the birdbath’s immediate left, oriented toward it, while the squirrel is on the right side, turned 180° away.',
            'Assessment Point': 'Centered placement between symmetrical elements, left/right flanking with directional orientation, and 180° rotational positioning.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 95,
        },
        {
            'Prompt': 'Arrange a dining plate centrally. Place a fork to its left, a knife to its right, a spoon above aligned with the plate’s top edge, and a napkin beneath the fork.',
            'Reference Caption': 'The plate is centered. Fork on the left, knife on the right, spoon horizontally centered above the plate’s top rim. The napkin is positioned directly under the fork, not overlapping the plate.',
            'Assessment Point': 'Cardinal directions relative to central object (left/right/above/beneath)',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 96,
        },
        {
            'Prompt': 'In a parking lot, park a red car left of a blue truck. Position a motorcycle facing away in front of the truck. Lean a bicycle against a pole behind the red car.',
            'Reference Caption': 'Red car (left) and blue truck (right) are parallel. Motorcycle faces backward in front of the truck. Bicycle leans vertically against a pole placed behind the red car’s bumper.',
            'Assessment Point': 'Lateral vehicle positioning (left/right/front/behind) with orientation',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 97,
        },
        {
            'Prompt': 'On a kitchen counter, place a blender in the back left corner. Put a cutting board in front of it, a knife horizontally on the board, and a fruit bowl near the counter’s right edge, right of the blender.',
            'Reference Caption': 'Blender occupies the back left corner. Cutting board is centered in front of the blender, knife laid horizontally across it. Fruit bowl is on the counter’s far right edge, no overlap with other items.',
            'Assessment Point': 'Corner placement and front/right alignment in kitchen layout',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 98,
        },
        {
            'Prompt': 'In a bathroom, hang a towel on a rack right of the shower. Place a bathmat directly in front of the shower door. Mount a shelf above the toilet with a candle and plant.',
            'Reference Caption': 'Towel rack is adjacent to the shower’s right side. Bathmat is centered in front of the closed shower door. Shelf is mounted on the wall above the toilet tank, holding both candle and plant.',
            'Assessment Point': 'Adjacent positioning (right/front/above) in bathroom fixtures',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 99,
        },
        {
            'Prompt': 'Set up a round patio table with two chairs opposite each other (12 and 6 o’clock). Open an umbrella through the table’s center hole. Place a drink at the 3 o’clock table edge.',
            'Reference Caption': 'Chairs face each other across the table’s diameter. Umbrella rises vertically through the table’s center. Drink is positioned at the table’s rightmost edge (3 o’clock) without overlapping the chairs.',
            'Assessment Point': 'Clock position alignment and vertical/horizontal relationships',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 100,
        },
        {
            'Prompt': 'On a bookshelf, position a potted plant on the top shelf’s left edge. Center a photo frame on the middle shelf. Stack books on the bottom shelf, aligned with the frame’s right side.',
            'Reference Caption': 'Plant is on the top shelf’s far left. Photo frame is centered on the middle shelf. Books are stacked on the bottom shelf, their left edge aligned with the frame’s right edge.',
            'Assessment Point': "Edge alignment (top shelf left, bottom shelf aligned with frame's right) and vertical positioning across shelves",
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 101,
        },
        {
            'Prompt': 'In a classroom, center the teacher’s desk at the front. Mount a whiteboard behind it. Place a student desk to the teacher desk’s left, facing it, and a bookshelf parallel to the right wall.',
            'Reference Caption': 'Teacher’s desk is front-center. Whiteboard covers the wall behind it. Student desk is left of the teacher’s desk, angled toward it. Bookshelf runs parallel to the right wall, not touching the teacher’s desk.',
            'Assessment Point': 'Directional relationships (left/behind), object orientation (facing/parallel), and spatial organization in room layouts',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 102,
        },
        {
            'Prompt': 'On a nightstand, place an alarm clock at the back. Position a book horizontally in front of the clock. Add a glass of water to the nightstand’s right edge, ahead of the book.',
            'Reference Caption': 'Alarm clock is at the nightstand’s rear. Book lies flat, horizontally centered between the clock and the nightstand’s front edge. Glass is on the far right edge, closer to the front than the book.',
            'Assessment Point': 'Front/back positioning and horizontal vs edge placement with multiple objects on a surface',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 103,
        },
        {
            'Prompt': 'A microwave is mounted above a stove, with a coffee mug placed inside it. A spatula leans vertically against the microwave’s slightly open door.',
            'Reference Caption': 'The microwave is positioned directly above the stove. The coffee mug is fully inside the microwave, visible through the partially open door. The spatula stands upright, touching the microwave door’s exterior edge (not inside).',
            'Assessment Point': 'Vertical alignment (above/below), containment (inside/outside), and external object placement relative to appliances',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 104,
        },
        {
            'Prompt': 'On the middle shelf of a bookshelf, position a red book to the left of a blue vase. On the shelf above, center a small potted plant aligned directly over the vase.',
            'Reference Caption': 'The red book is placed left of the blue vase on the middle shelf. The plant on the upper shelf is centered horizontally and vertically aligned with the vase below.',
            'Assessment Point': 'Horizontal positioning (left/right) combined with vertical alignment across multiple shelves',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 105,
        },
        {
            'Prompt': 'Park a bicycle facing east to the right of a park bench. Position a trash can behind the bench at a 45-degree angle relative to the bicycle’s front wheel.',
            'Reference Caption': 'The bicycle is on the bench’s right side, front wheel pointing east. The trash can is behind the bench, placed such that its center forms a diagonal line with the bicycle’s front wheel.',
            'Assessment Point': 'Relative positioning (right/behind) and angular alignment between objects',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 106,
        },
{
    'Prompt': 'A dining table has a fruit bowl centered on it. Place two identical candles—one slightly to the left of the bowl, the other slightly to the right. Hang a circular mirror on the wall behind, aligned with the bowl’s center.',
    'Reference Caption': 'The candles are symmetrically placed on either side of the bowl. The mirror is centered on the wall, its vertical axis matching the bowl’s center point.',
    'Assessment Point': 'Symmetrical lateral placement (left/right) and vertical alignment with a central object using approximate distance language.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 107,
},
{
    'Prompt': 'A monitor is centered on a desk. Position a keyboard just in front of the monitor. Place a desk lamp to the monitor’s left, angled 30 degrees toward the keyboard.',
    'Reference Caption': 'The keyboard is directly in front of the monitor with a clear gap. The lamp is on the left side, tilted so its light direction points toward the keyboard.',
    'Assessment Point': 'Directional placement (front/left) and angular orientation toward specified objects, with natural spacing language.',
    'Category': 'Compositional',
    'Subcategory': 'Prescriptive Spatial',
    'id': 108,
},
        {
            'Prompt': 'A birdbath is centered in a garden. Flanking it on either side are two flower beds—the left bed has sunflowers, the right has tulips. A stone path starts behind the birdbath and curves westward.',
            'Reference Caption': 'The birdbath is the central focal point. Sunflowers are strictly to its left, tulips to its right. The path begins directly behind the birdbath and bends leftward.',
            'Assessment Point': 'Lateral object distinction (left/right) and path orientation relative to a central feature',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 109,
        },
        {
            'Prompt': 'In a classroom, position the teacher’s desk facing rows of student desks. Mount a whiteboard behind the teacher’s desk, with a clock to the whiteboard’s right. Place a bookshelf in the rear left corner, touching the door frame.',
            'Reference Caption': 'The teacher’s desk faces forward, whiteboard directly behind it. The clock is on the wall to the whiteboard’s immediate right. The bookshelf is in the back left corner, flush with the door.',
            'Assessment Point': 'Understanding relative positioning (behind, right, left) and corner placement relative to reference objects.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 110,
        },
        {
            'Prompt': 'A coffee table sits between a sofa and TV stand. Arrange a remote control on the table’s left edge, parallel to the sofa. Place a magazine at the table’s right edge, angled 45 degrees toward the TV.',
            'Reference Caption': 'The remote is aligned straight (parallel to the sofa) on the table’s left side. The magazine is on the right edge, tilted diagonally to face the TV.',
            'Assessment Point': 'Interpreting edge-based placement, angular orientation (45°), and parallel alignment relative to objects.',
            'Category': 'Compositional',
            'Subcategory': 'Prescriptive Spatial',
            'id': 111,
        },
    ]

